#!/bin/sh
# force color
# no TERM variable is available by the time is run by dynamic MOTD, so no color codes are included in the output
# https://unix.stackexchange.com/questions/411966/why-does-ssh-kill-the-colour-in-my-etc-update-motd-d-script-when-force-color-p
export TERM=xterm-256color

# get the uptime string to printf
upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`

# get the load averages
read one five fifteen rest < /proc/loadavg

tput setaf 2
cat << "EOF"
Welcome on,
EOF

tput setaf 236
cat << "EOF"
   __                 _ __    __      _ _
EOF
tput setaf 238
cat << "EOF"
  /__\ __ _ ___ _ __ (_) / /\ \ \__ _| | |
EOF
tput setaf 240
cat << "EOF"
 / \/// _` / __| '_ \| \ \/  \/ / _` | | |
EOF
tput setaf 242
cat << "EOF"
/ _  \ (_| \__ \ |_) | |\  /\  / (_| | | |
EOF
tput setaf 244
cat << "EOF"
\/ \_/\__,_|___/ .__/|_| \/  \/ \__,_|_|_|.debianium.com
EOF
tput setaf 245
cat << "EOF"
               |_|

EOF
tput setaf 246
date +"%A, %e %B %Y, %r"
tput setaf 247
uname -srmo
tput setaf 248
echo "Uptime.............: ${UPTIME}"
tput setaf 249
echo "Memory.............: `cat /proc/meminfo | grep MemFree | awk {'print $2'}`kB (Free) / `cat /proc/meminfo | grep MemTotal | awk {'print $2'}`kB (Total)"
tput setaf 250
echo "Load Averages......: ${one}, ${five}, ${fifteen} (1, 5, 15 min)"
tput setaf 251
echo "Running Processes..: `ps ax | wc -l | tr -d " "`"
tput setaf 252
# echo "IP Addresses.......: Local `ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/` and public `wget -T 1 -q -O - http://icanhazip.com/ | tail`"
tput setaf 253
echo "Pocasi Mnisek .....: `curl -m 2 -s "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=CZ|CZ|25210|PRAHA|" | sed -n '/Currently:/ s/.*: \(.*\): \([0-9]*\)\([CF]\).*/\2°\3, \1/p'`"

echo ""
tput sgr0

